allowBuilds:
  aws-sdk: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-bedrock-agentcore@3.1053.0'
  - '@aws-sdk/client-bedrock-agentcore@3.1057.0'
  - '@aws-sdk/credential-provider-ini@3.972.46'
  - '@aws-sdk/credential-provider-node@3.972.47'
  - '@dotenvx/dotenvx@1.69.2'
  - '@smithy/credential-provider-imds@4.3.6'
  - cdk-ecr-deployment@4.2.8
minimumReleaseAgeStrict: false
